site_name: ✝️小彭大典✝️
nav:
  - 前言: index.md
  - 大典:
    - helloworld.md
    - platform.md
    - vartypes.md
    - functions.md
    - functional.md
    - unicode.md
  - GitHub: https://github.com/parallel101/cppguidebook
  - Bilibili: https://space.bilibili.com/263032155
plugins:
  - search
  - print-site
  - macros
