site_name: ✝️小彭大典✝️
nav:
  - 章节列表:
    - index.md
    - start.md
    - helloworld.md
    - platform.md
    - vartypes.md
    - functions.md
    - functional.md
    - unicode.md
  - GitHub: https://github.com/parallel101/cppguidebook
  - Bilibili: https://space.bilibili.com/263032155
plugins:
  - search
  - print-site
  - macros
theme:
  name: mkdocs
  palette:
    primary: blue grey
  font:
    code: Noto Sans Simplified Chinese
  features:
    - search.suggest
    - search.highlight
