name: Generate Release PDF
# 感谢 Derived Cat (@hooyuser) 提供的自动发布小脚本！

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '**.md'

env:
  MIRROR_SITE_URL: https://142857.red/files
  MIRROR_SITE_HOOK: https://142857.red/hooks/update_cppguidebook
  MIRROR_SITE_TOKEN: ${{ secrets.SEVEN_TOKEN }}

jobs:
  build_typst:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          pip install mkdocs
          pip install mkdocs-print-site-plugin
          pip install mkdocs-macros-plugin
          npm i -g puppeteer

      - name: Compile document
        run: |
          mkdocs build
          node export_to_pdf.js files://$PWD/site/print_page.html cppguidebook.pdf "小彭老师的现代 C++ 大典"

      - name: Delete old Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo
            try {
              const { data: { id } } = await github.rest.repos.getLatestRelease({ owner, repo })
              await github.rest.repos.deleteRelease({ owner, repo, release_id: id })
            } catch {}

      - name: Generate release tag
        id: tag
        run: |
          echo "release_date=$(date +"%Y 年 %m 月 %d 日 %H 点 %M 分")" >> $GITHUB_OUTPUT
          echo "release_tag=latest_$(date +"%Y-%m-%d_%H-%M")" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 伟大，无需多言
          body: |
            小彭老师发布的最新 C++ 大典，更新时间 ${{ steps.tag.outputs.release_date }}
            > Release 页面太慢？GitHub 卡顿，无法下载？访问 [小彭老师自己维护的镜像](${{ env.MIRROR_SITE_URL }}/cppguidebook.pdf)。
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: cppguidebook.pdf

      - name: Publish to mirror site
        continue-on-error: true
        run: |
          curl -L -X POST ${{ env.MIRROR_SITE_HOOK }} -d token=${{ env.MIRROR_SITE_TOKEN }} -d tag=${{ steps.tag.outputs.release_tag }}
